# Version: 0.0.1
FROM debian:8.5
MAINTAINER maintainer_name "maintainer_email"
RUN apt-get update
RUN apt-get install -y nginx
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80:80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
